export const NOTIFICATION_MESSAGE: Record<string, string> = {
  "AGH-202": "Tài khoản chưa được kích hoạt",
  "AGH-203": "Email hoặc mật khẩu không chính xác",
  "AGH-205": "Bạn không có quyền hạn để thực hiện hành động này",
  "AGH-305": "Email đã được sử dụng",
  "AGH-306": "Quyền hạn đang được sử dụng",
  "AGH-307": "Đơn vị không tồn tại",
  "AGH-308": "Đơn vị đã tồn tại",
  "AGH-309": "Danh mục sản phẩm không tồn tại",
  "AGH-310": "Danh mục sản phẩm đã tồn tại",
  "AGH-311": "Sản phẩm không tồn tại",
  "AGH-312": "Sản phẩm đã tồn tại",
  "AGH-313": "Nhà cung cấp không tồn tại",
  "AGH-314": "Nhà cung cấp đã tồn tại",
  "AGH-315": "Kho hàng không tồn tại",
  "AGH-316": "Kho hàng đã tồn tại",
  "AGH-318": "Vị trí hàng hóa không tồn tại",
  "AGH-319": "Vị trí hàng hóa đã tồn tại",
};
