server:
  port: 8080

spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
application:
  security:
    rsa:
      rsa-public-key: classpath:certs/public-key.pem
      rsa-private-key: classpath:certs/private-key.pem
    jwt:
      access-token-validity-in-seconds: 604800 # 1 day
      refresh-token-validity-in-seconds: 604800 # 7 days