networks:
  agrohub:
    external: true
services:
  auth-service:
    build: ./auth-service
    image: agrohub/auth-service:dev
    container_name: auth-service
    env_file:
      - ./auth-service/.env.docker
    ports:
      - "8080:8080"
    networks:
      - agrohub