networks:
  agrohub:
    external: true
services:
  user-service:
    build: ./user-service
    image: agrohub/user-service:dev
    container_name: user-service
    env_file:
      - ./user-service/.env.docker
    ports:
      - "8080:8080"
    networks:
      - agrohub