networks:
  agrohub:
    external: true
services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile.dev
    image: agrohub/user-service:dev
    container_name: user-service
    env_file:
      - user-service/.env.docker
    ports:
      - "8080:8080"
    networks:
      - agrohub

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile.dev
    image: agrohub/product-service:dev
    container_name: product-service
    env_file:
      - product-service/.env.docker
    ports:
      - "8081:8081"
    networks:
      - agrohub

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile.dev
    image: agrohub/inventory-service:dev
    container_name: inventory-service
    env_file:
      - inventory-service/.env.docker
    ports:
      - "8082:8082"
    networks:
      - agrohub

  purchase-service:
    build:
      context: .
      dockerfile: purchase-service/Dockerfile.dev
    image: agrohub/purchase-service:dev
    container_name: purchase-service
    env_file:
      - purchase-service/.env.docker
    ports:
      - "8083:8083"
    networks:
      - agrohub

  debt-service:
    build:
      context: .
      dockerfile: debt-service/Dockerfile.dev
    image: agrohub/debt-service:dev
    container_name: debt-service
    env_file:
      - debt-service/.env.docker
    ports:
      - "8084:8084"
    networks:
      - agrohub

  customer-service:
    build:
      context: .
      dockerfile: customer-service/Dockerfile.dev
    image: agrohub/customer-service:dev
    container_name: customer-service
    env_file:
      - customer-service/.env.docker
    ports:
      - "8085:8085"
    networks:
      - agrohub

  sales-service:
    build:
      context: .
      dockerfile: sales-service/Dockerfile.dev
    image: agrohub/sales-service:dev
    container_name: sales-service
    env_file:
      - sales-service/.env.docker
    ports:
      - "8086:8086"
    networks:
      - agrohub

  email-service:
    build:
      context: .
      dockerfile: email-service/Dockerfile.dev
    image: agrohub/email-service:dev
    container_name: email-service
    env_file:
      - email-service/.env.docker
    ports:
      - "8087:8087"
    networks:
      - agrohub