server:
  port: 8085
  servlet:
    context-path: /customer-service
spring:
  application:
    name: customer-service
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    servers: ${AXON_SERVER}
  eventhandling:
    processors:
      customer-group:
        mode: subscribing
application:
  security:
    rsa:
      rsa-public-key: classpath:certs/public-key.pem