server:
  port: 8084
  servlet:
    context-path: /debt-service
spring:
  application:
    name: debt-service
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    servers: ${AXON_SERVER}
  eventhandling:
    processors:
      debt-group:
        mode: subscribing
      debt-transactions-group:
        mode: subscribing
      payment-group:
        mode: subscribing
application:
  security:
    rsa:
      rsa-public-key: classpath:certs/public-key.pem