server:
  port: 8081
  servlet:
    context-path: /product-service
spring:
  application:
    name: product-service
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 10MB
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    servers: ${AXON_SERVER}
  serializer:
    general: jackson
    messages: jackson
    events: jackson
  eventhandling:
    processors:
      product-group:
        mode: subscribing
      unit-group:
        mode: subscribing
      category-group:
        mode: subscribing
application:
  security:
    rsa:
      rsa-public-key: classpath:certs/public-key.pem
cloudinary:
  url: ${CLOUDINARY_URL}