server:
  port: 8081
  servlet:
    context-path: /product-service
spring:
  application:
    name: product-service
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    servers: ${AXON_SERVER}
  serializer:
    general: jackson
    messages: jackson
    events: jackson
application:
  security:
    rsa:
      rsa-public-key: classpath:certs/public-key.pem